Controllers/BusinessController.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Models.CustomerModels;
using static System.Net.Mime.MediaTypeNames;
using System.Text;
using System.Text.Json;
using MovieApp.Models.BusinessModels;

namespace MovieApp.Controllers
{

    public class BusinessController : Controller
    {
        private readonly IHttpClientFactory _clientFactory;
        private readonly IConfiguration _config;

        public BusinessController(IHttpClientFactory clientFactory, IConfiguration config)
        {
            _clientFactory = clientFactory;
            _config = config;
        }
        [HttpGet]
        public async Task<IActionResult> GetStaff()
        {
            var client = _clientFactory.CreateClient();

            HttpResponseMessage response = await client.GetAsync(_config.GetConnectionString("Default") + "Staff/");

            if (response.IsSuccessStatusCode)
            {
                var stream = await response.Content.ReadAsStringAsync();
                var data = JsonSerializer.Deserialize<List<staff>>(stream);

                return View(data);
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> UpdateStaff(int id)
        {
            var client = _clientFactory.CreateClient();

            HttpResponseMessage response = await client.GetAsync(_config.GetConnectionString("Default") + $"Staff/{id}");

            if (response.IsSuccessStatusCode)
            {
                var stream = await response.Content.ReadAsStringAsync();
                var data = JsonSerializer.Deserialize<staff>(stream);

                return View(data);
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UpdateStaff(staff? staff)
        {
            var staffDataJson = new StringContent(
                    JsonSerializer.Serialize(staff),
                    Encoding.UTF8,
                    Application.Json);

            var client = _clientFactory.CreateClient();

            HttpResponseMessage response = await client.PutAsync(_config.GetConnectionString("Default") + "Staff/", staffDataJson);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetStaff");
            }
            return View();
        }
        public async Task<IActionResult> DeleteStaff(int id)
        {
            var client = _clientFactory.CreateClient();

            HttpResponseMessage response = await client.DeleteAsync(_config.GetConnectionString("Default") + $"Staff/?id={id}");

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetStaff");
            }
            return RedirectToAction("GetStaff");
        }
        [HttpGet]
        public IActionResult CreateStaff()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateStaff(staff staff)
        {
            if (ModelState.IsValid)
            {
                var client = _clientFactory.CreateClient();

                var staffaddrDataJson = new StringContent(
                    JsonSerializer.Serialize(staff),
                    Encoding.UTF8,
                    Application.Json);

                HttpResponseMessage response = await client.PostAsync(_config.GetConnectionString("Default") + "StaffAddress/", staffaddrDataJson);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("GetStaff");
                }
            }
            return View();
        }
    }
}

Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Models.CustomerModels;
using static System.Net.Mime.MediaTypeNames;
using System.Text;
using System.Text.Json;
using System.IO;

namespace MovieApp.Controllers;

public class CustomerController : Controller
{
    private readonly IHttpClientFactory _clientFactory;
    private readonly IConfiguration _config;

    public CustomerController(IHttpClientFactory clientFactory, IConfiguration config)
    {
        _clientFactory = clientFactory;
        _config = config;
    }
    [HttpGet]
    public async Task<IActionResult> GetAllCustomers()
    {
        var client = _clientFactory.CreateClient();

        HttpResponseMessage response = await client.GetAsync(_config.GetConnectionString("Default") + "Customers/");

        if (response.IsSuccessStatusCode)
        {
            var stream = await response.Content.ReadAsStringAsync();
            var data = JsonSerializer.Deserialize<List<customer>>(stream);

            return View(data);
        }
        return View();
    }
    [HttpGet]
    public async Task<IActionResult> UpdateCustomer(int id)
    {
        var client = _clientFactory.CreateClient();

        HttpResponseMessage response = await client.GetAsync(_config.GetConnectionString("Default") + $"Customers/{id}");

        if (response.IsSuccessStatusCode)
        {
            var stream = await response.Content.ReadAsStringAsync();
            var data = JsonSerializer.Deserialize<customer>(stream);

            return View(data);
        }
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> UpdateCustomer(customer? customer)
    {
        var customerDataJson = new StringContent(
                JsonSerializer.Serialize(customer),
                Encoding.UTF8,
                Application.Json);

        var client = _clientFactory.CreateClient();

        HttpResponseMessage response = await client.PutAsync(_config.GetConnectionString("Default") + "Customers/", customerDataJson);

        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction("GetAllCustomers");
        }
        return View();
    }

    public async Task<IActionResult> DeleteCustomer(int id)
    {
        var client = _clientFactory.CreateClient();

        HttpResponseMessage response = await client.DeleteAsync(_config.GetConnectionString("Default") + $"Customers/?id={id}");

        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction("GetAllCustomers");
        }
        return RedirectToAction("GetAllCustomers");
    }
    public IActionResult CreateCustomer()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> CreateCustomer(customer customerData)
    {
        if (ModelState.IsValid)
        {
            var client = _clientFactory.CreateClient();

            var customerDataJson = new StringContent(
                JsonSerializer.Serialize(customerData),
                Encoding.UTF8,
                Application.Json);

            HttpResponseMessage response = await client.PostAsync(_config.GetConnectionString("Default") + "Customers/", customerDataJson);

            if (response.IsSuccessStatusCode)
            {
                return View("CreateCustomer");
            }
        }
        return View();
    }
    public IActionResult CreateAddress()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> CreateAddress(address addressData)
    {
        if (ModelState.IsValid)
        {
            //var request = new HttpRequestMessage(
            //    HttpMethod.Post,
            //    "https://localhost:7110/Customers/");

            var client = _clientFactory.CreateClient();

            var customerDataJson = new StringContent(
                JsonSerializer.Serialize(addressData),
                Encoding.UTF8,
                Application.Json);

            HttpResponseMessage response = await client.PostAsync(_config.GetConnectionString("Default") + "Addresses/", customerDataJson);

            if (response.IsSuccessStatusCode)
            {
                return View("CreateAddress");
            }
        }
        return View();
    }
    [HttpGet]
    public IActionResult Customer_Address()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Customer_Address(customer customer)
    {
        if (ModelState.IsValid)
        {
            var client = _clientFactory.CreateClient();

            var custaddrDataJson = new StringContent(
                JsonSerializer.Serialize(customer),
                Encoding.UTF8,
                Application.Json);

            HttpResponseMessage response = await client.PostAsync(_config.GetConnectionString("Default") + "CustomersAddress/", custaddrDataJson);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetAllCustomers");
            }
        }
        return View();
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dashboard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieApp.styles.css" asp-append-version="true" />
</head>
<body>
    <div class ="d-flex flex-column" style="height: 100vh;">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
                <div class="container-fluid">
                    <a class="navbar-brand" style="user-select: none;">Dashboard</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
@*                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="CreateCustomer">Create Customer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="CreateAddress">Create Address</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Customer_Address">Customer Address</a>
                            </li>
                        </ul>*@
                    </div>
                </div>
            </nav>
        </header>
        <div class="d-flex flex-grow-1">
        @*SIDEBAR*@
            <div class="sticky-top d-flex flex-column" id="accordion" style="width: 240px; background-color: #1e1d6e;">
                @*CUSTOMER*@
                <div class="card tab1" style="border-radius: 0;">
                    <div class="card-header p-0">
                        <a class="btn p-3" data-bs-toggle="collapse" href="#collapseOne" draggable="false" style="width: 100%; height: 100%;">
                            Customers
                        </a>
                    </div>
                    <div id="collapseOne" class="collapse" data-bs-parent="#accordion">
                        <div class="card-body d-flex flex-column p-0">
                            <a class="btn btn-list" asp-controller="Customer" asp-action="GetAllCustomers">All Customers</a>
                            <a class="btn btn-list" asp-controller="Customer" asp-action="Customer_Address">Add Customer</a>
                            @*<a class="btn btn-list" asp-controller="Customer" asp-action="CreateCustomer">Add Customer</a>*@
                        </div>
                    </div>
                </div>
                @*BUSINESS*@
                <div class="card tab2" style="border-radius: 0;">
                    <div class="card-header p-0">
                        <a class="collapsed btn p-3" data-bs-toggle="collapse" href="#collapseTwo" draggable="false" style="width: 100%; height: 100%;">
                            Staff
                        </a>
                    </div>
                    <div id="collapseTwo" class="collapse" data-bs-parent="#accordion">
                        <div class="card-body d-flex flex-column p-0">
                            <a class="btn btn-list" asp-controller="Business" asp-action="GetStaff">Get All Staff</a>
                            <a class="btn btn-list" asp-controller="Business" asp-action="CreateStaff">Add Staff</a>
                        </div>
                    </div>
                </div>
                @*MOVIES*@
      @*          <div class="card tab3" style="border-radius: 0;">
                    <div class="card-header">
                        <a class="collapsed btn" data-bs-toggle="collapse" href="#collapseThree" draggable="false">
                            Sales
                        </a>
                    </div>
                    <div id="collapseThree" class="collapse" data-bs-parent="#accordion">
                        <div class="card-body d-flex flex-column p-0">
                            <a class="btn btn-list">All Customers</a>
                            <a class="btn btn-list">Add Customer</a>
                        </div>
                    </div>
                </div>*@
                
            </div>
            @*END SIDEBAR*@
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>